# Site settings
title: Blog de @johnnywalls
email: 
description: > # this means to ignore newlines until "baseurl:"
  Cualquier cosa sobre programación, tecnología de información u opiniones aleatorias.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnnywalls.github.io" # the base hostname & protocol for your site
twitter_username: johnnywalls
github_username:  johnnywalls

# Build settings
markdown: kramdown
